ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION}

# Build-time variables
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_CAS_SERVICE_URL
ARG NEXT_PUBLIC_API_VERSION=v1
ARG NEXT_PUBLIC_API_REQUEST_TIMEOUT=10000
ARG NEXT_PUBLIC_ETUUTT_WEB_APPLICATION_ID
ARG NEXT_PUBLIC_AUTHORIZATION_TOKEN_EXPIRES_IN=2592000
ARG NEXT_PUBLIC_ASSOCIATION_NAME
ARG NEXT_PUBLIC_ASSOCIATION_RNA
ARG NEXT_PUBLIC_ASSOCIATION_RCS
ARG NEXT_PUBLIC_ASSOCIATION_ADDRESS
ARG NEXT_PUBLIC_ASSOCIATION_PHONE
ARG NEXT_PUBLIC_ASSOCIATION_EMAIL
ARG NEXT_PUBLIC_DPO_EMAIL
ARG NEXT_PUBLIC_DPO_NAME
ARG NEXT_PUBLIC_PUBLICATION_DIRECTOR
ARG NEXT_PUBLIC_LAST_TERMS_UPDATE='02/04/2024'
ARG NEXT_PUBLIC_LAST_PRIVACY_POLICY_UPDATE='02/04/2024'

# Runtime variables
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_CAS_SERVICE_URL=${NEXT_PUBLIC_CAS_SERVICE_URL}
ENV NEXT_PUBLIC_API_VERSION=${NEXT_PUBLIC_API_VERSION}
ENV NEXT_PUBLIC_API_REQUEST_TIMEOUT=${NEXT_PUBLIC_API_REQUEST_TIMEOUT}
ENV NEXT_PUBLIC_ETUUTT_WEB_APPLICATION_ID=${NEXT_PUBLIC_ETUUTT_WEB_APPLICATION_ID}
ENV NEXT_PUBLIC_AUTHORIZATION_TOKEN_EXPIRES_IN=${NEXT_PUBLIC_AUTHORIZATION_TOKEN_EXPIRES_IN}
ENV NEXT_PUBLIC_ASSOCIATION_NAME=${NEXT_PUBLIC_ASSOCIATION_NAME}
ENV NEXT_PUBLIC_ASSOCIATION_RNA=${NEXT_PUBLIC_ASSOCIATION_RNA}
ENV NEXT_PUBLIC_ASSOCIATION_RCS=${NEXT_PUBLIC_ASSOCIATION_RCS}
ENV NEXT_PUBLIC_ASSOCIATION_ADDRESS=${NEXT_PUBLIC_ASSOCIATION_ADDRESS}
ENV NEXT_PUBLIC_ASSOCIATION_PHONE=${NEXT_PUBLIC_ASSOCIATION_PHONE}
ENV NEXT_PUBLIC_ASSOCIATION_EMAIL=${NEXT_PUBLIC_ASSOCIATION_EMAIL}
ENV NEXT_PUBLIC_DPO_EMAIL=${NEXT_PUBLIC_DPO_EMAIL}
ENV NEXT_PUBLIC_DPO_NAME=${NEXT_PUBLIC_DPO_NAME}
ENV NEXT_PUBLIC_PUBLICATION_DIRECTOR=${NEXT_PUBLIC_PUBLICATION_DIRECTOR}
ENV NEXT_PUBLIC_LAST_TERMS_UPDATE=${NEXT_PUBLIC_LAST_TERMS_UPDATE}
ENV NEXT_PUBLIC_LAST_PRIVACY_POLICY_UPDATE=${NEXT_PUBLIC_LAST_PRIVACY_POLICY_UPDATE}
ENV NODE_ENV=production
ENV CI=true

WORKDIR /usr/src/app

# Add alpine dependencies for 'sharp'
RUN apk add --upgrade --no-cache vips-dev build-base

COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN npm i -g pnpm@10 && pnpm install --frozen-lockfile --prod=false --ignore-scripts=false

COPY --chown=node:node . .

RUN pnpm next build

ENV NODE_ENV=production
ENV CI=true

RUN pnpm install -P

USER node

CMD ["pnpm", "next", "start", "-p", "8080"]
