import styles from './layout.module.scss';
import '@/global.scss';
import Providers from '@/lib/Providers';
import React, { ReactNode } from 'react';
import Redirecter from '@/components/utilities/Redirecter';
import AutoLogin from '@/components/utilities/AutoLogin';
import Wrapper from '@/components/utilities/Wrapper';
import PageSearchParams from '@/components/utilities/PageSearchParams';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <Providers>
        <Redirecter />
        <AutoLogin />
        <PageSearchParams />
        <body>
          <Wrapper>{children}</Wrapper>
        </body>
      </Providers>
    </html>
  );
}
